[project]
name = "forum-cloud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "nltk>=3.9.2",
    "pip>=26.0",
    "spacy>=3.8.11",
    "wordcloud>=1.9.6",
]
